### PR TITLE
Str replace when function

### LINKED ISSUE #15: Add function `str_replace_when` as vectorized form of `str_replace`
in regular form if you're needing to use regex but have numerous strings you need to replace, it would look like:
```
mutate(chemical = str_replace(chemical, "\\-Total$", ""),
       chemical = str_replace(chemical, "\\-SO4", "(SO4)"))
```
and in the `case_when`  format, in order to do multiple `str_replace`  you have to do both a `str_detect` and `str_replace` , (which is even more bulky and repetitive) like so:
```
mutate(chemical = case_when(str_detect(chemical, "\\-Total$") ~ str_replace(chemical,  "\\-Total$", ""),
                            str_detect(chemical, "\\-SO4") ~ str_replace(chemical, "\\-SO4", "(SO4)"),
                            TRUE ~ chemical))
```
i'm not totally sure how it could be written out but in an ideal form, a vectorized `str_replace`  would look something like:
```
mutate(chemical = str_replace_when(chemical, "\\-Total$", "",
                                   chemical, "\\-SO4", "(SO4)"))
```
or in a `case_when` format, it would still require a `str_detect` so something like:
```
mutate(chemical = str_replace_when(str_detect(chemical, "\\-Total$") ~ "",
                                   str_detect(chemical, "\\-SO4") ~ "(SO4)",
                                   TRUE ~ chemical))
```

### PR DESCRIPTION
**Pull request by nadinehussein**
closes #15

### CODE REVIEW

**Review by joethorley — COMMENTED** [review]
Looks great - can you add tests for more edge cases like x of no length and replace of no length. Also you only need to use mutate for one test that it works with mutate. You can just use a straight vector without it being a column of a dataset for the rest. Also in the documentation you can just can be used to replace multiple strings in a vector.

**Review by joethorley — CHANGES_REQUESTED** [review]
see previous comment

**Comment by nadinehussein** [comment]
> Looks great - can you add tests for more edge cases like x of no length and replace of no length. Also you only need to use mutate for one test that it works with mutate. You can just use a straight vector without it being a column of a dataset for the rest. Also in the documentation you can just can be used to replace multiple strings in a vector.

tests have been changed and description was updated - I wanted to mention the difference between the function and `str_replace_all` because we don't need to create a `str_replace_all` version of `str_replace_vec` since `str_replace_all` can already do vectorized forms.

**Review by joethorley — COMMENTED** [review]
great

**Review by joethorley — APPROVED** [review]

**Pull request merged**
